name: 🐛 Bug Report
description: Report a problem with SynapseStack
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report
        
        Thanks for taking the time to report a bug! Please provide the details below to help identify and fix the issue.

  - type: dropdown
    id: severity
    attributes:
      label: Impact Level
      description: How does this affect your SynapseStack installation?
      options:
        - "🔴 Critical - SynapseStack won't start or completely broken"
        - "🟡 High - Major feature not working"
        - "🟢 Medium - Feature partially working or workaround exists"
        - "⚪ Low - Minor issue or cosmetic problem"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug and what you expected to happen instead
      placeholder: "Clear description of the issue..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can the issue be reproduced?
      placeholder: |
        1. Start SynapseStack with `./synapsestack start`
        2. Open web interface at http://localhost:8443
        3. Click on '...'
        4. See error: ...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: System Information
      description: Help understand your deployment environment
      placeholder: |
        - SynapseStack Version: [e.g. v1.0.0 or commit hash]
        - OS: [e.g. Ubuntu 22.04, Rocky Linux 9]
        - Hardware: [e.g. 8-core CPU, 32GB RAM, RTX 4090]
        - Container Runtime: [e.g. Podman 4.8.1]
        - Installation Method: [e.g. .deb package, static binary]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs or Error Messages
      description: Paste any relevant log output or error messages
      placeholder: |
        ```
        [Paste logs here - check /opt/synapsestack/logs/ or console output]
        ```

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Screenshots, configuration files, or anything else that might help
      placeholder: "Any other details that might be helpful..."